packages:
  - apps/**
  - modules/**
  - packages/**
  - smoke-tests

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - msw
  - netlify-cli
  - protobufjs
  - sharp
  - unix-dgram
